"""Add global statistics table

Revision ID: 273e0fbbf7b9
Revises: 9fc5a178d2a7
Create Date: 2025-10-13 21:22:09.763078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273e0fbbf7b9'
down_revision: Union[str, None] = '9fc5a178d2a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
