"""Initial schema

Revision ID: 9fc5a178d2a7
Revises: 
Create Date: 2025-10-13 14:50:32.172166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fc5a178d2a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('street_name', sa.String(length=255), nullable=True),
    sa.Column('speed_limit', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('share_community', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_sync', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_index('ix_devices_location', 'devices', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_devices_owner_active', 'devices', ['owner_id', 'is_active'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('share_data_community', sa.Boolean(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('device_api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_index('ix_device_api_keys_device_active', 'device_api_keys', ['device_id', 'is_active'], unique=False)
    op.create_index('ix_device_api_keys_hash', 'device_api_keys', ['api_key_hash'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_vehicles', sa.Integer(), nullable=True),
    sa.Column('speeding_vehicles', sa.Integer(), nullable=True),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_device_dates', 'reports', ['device_id', 'start_date', 'end_date'], unique=False)
    op.create_index('ix_reports_user_created', 'reports', ['user_id', 'created_at'], unique=False)
    op.create_table('speed_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('speed', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('speed_limit', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_speeding', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_speed_events_device_speeding', 'speed_events', ['device_id', 'is_speeding', 'timestamp'], unique=False)
    op.create_index('ix_speed_events_device_timestamp', 'speed_events', ['device_id', 'timestamp'], unique=False)
    op.create_index('ix_speed_events_speeding', 'speed_events', ['is_speeding', 'timestamp'], unique=False)
    op.create_index('ix_speed_events_timestamp', 'speed_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_speed_events_timestamp', table_name='speed_events')
    op.drop_index('ix_speed_events_speeding', table_name='speed_events')
    op.drop_index('ix_speed_events_device_timestamp', table_name='speed_events')
    op.drop_index('ix_speed_events_device_speeding', table_name='speed_events')
    op.drop_table('speed_events')
    op.drop_index('ix_reports_user_created', table_name='reports')
    op.drop_index('ix_reports_device_dates', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_device_api_keys_hash', table_name='device_api_keys')
    op.drop_index('ix_device_api_keys_device_active', table_name='device_api_keys')
    op.drop_table('device_api_keys')
    op.drop_table('user_preferences')
    op.drop_index('ix_devices_owner_active', table_name='devices')
    op.drop_index('ix_devices_location', table_name='devices')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
