"""Add is_admin field to users table

Revision ID: a8354bf2e7c1
Revises: 273e0fbbf7b9
Create Date: 2025-10-13 21:37:36.987589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8354bf2e7c1'
down_revision: Union[str, None] = '273e0fbbf7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))

    # Set default value for existing users (False for all existing users)
    op.execute("UPDATE users SET is_admin = FALSE WHERE is_admin IS NULL")

    # Set the first user (by created_at) as admin
    op.execute("""
        UPDATE users
        SET is_admin = TRUE
        WHERE id = (SELECT id FROM users ORDER BY created_at ASC LIMIT 1)
    """)

    # Now make the column non-nullable
    op.alter_column('users', 'is_admin', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
